(setq inhibit-startup-screen t)
(menu-bar-mode 0)
(tool-bar-mode 0)
(global-unset-key "\C-z")
(setq ring-bell-function 'ignore)
(setq-default indent-tabs-mode nil)
(global-display-line-numbers-mode t)
(savehist-mode 1)
(global-auto-revert-mode 1)
(defvar grep-save-buffers nil)
(use-package server
  :config
  (unless (server-running-p)
    (server-start)))
(setq scroll-conservatively 1)
(show-paren-mode)
