(global-set-key (kbd "C-<tab>") 'other-window)
(global-set-key (kbd "<C-S-iso-lefttab>")
  (lambda () (interactive) (other-window -1)))
(global-set-key (kbd "<C-S-tab>")
  (lambda () (interactive) (other-window -1)))
